# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jemoji

# Site settings
title: "Piyush Behre"
description: > # this means to ignore newlines until "email:"
   Thoughts

email: piyush.behre@hotmail.com
#blog logo
logo: "/assets/images/p_logo.png"
# blog cover
cover: "/assets/images/background_image.jpg"

name: 'Piyush Behre'
author: 'Piyush Behre'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://piyushbehre.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/piyushbehre
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/piyushbehre
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
