# Site settings
title: Piyush Behre
header-img: img/home-bg.jpg
email: piyush.behre@hotmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://www.piyushbehre.com"
twitter_username: piyushbehre
github_username:  piyushbehre
facebook_username:  PiyushBehre

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
